#!/bin/bash

name=$1
abbr=$2

if [ -z "$name" ]; then
	echo "usage: create_subject name [abbreviature for tex file]"
	exit 1
fi

[ -z "$abbr" ] && abbr=$(echo "$name" | tr -d ' ')

echo "Creating folder structure for subject $name. Filename: $abbr"

mkdir "$name"
cd "$name"

extra_folders="img pdf tex tikzgen"
extra_tex_files_suffixes="Ejs"
extra_tex_files_input=""

for folder in $extra_folders; do
	mkdir $folder
	touch $folder/.keep
	echo "Created directory $name/$folder with .keep file."
done

touch "$abbr.tex"

for suffix in $extra_tex_files_suffixes; do
	texfile="tex/${abbr}_${suffix}.tex"
	printf -v extra_tex_files_input "$extra_tex_files_input\n\chapter{---}\n\\input{$texfile}"
	echo "% -*- root: ../${abbr}.tex -*-" > $texfile
	echo "Created extra file $texfile"
done

current_year=$(date +%y)

if [ $(date +%m ) -ge 08 ] ; then # ¿Primer o segundo cuatrimestre?
	docdate="$current_year/$((current_year + 1)) C1"
else
	docdate="$((current_year - 1))/$current_year C2"
fi


cat << EOF > "$abbr.tex"
\documentclass[palatino]{apuntes}

\title{$name}
\author{}
\date{$docdate}

% Paquetes adicionales

% --------------------

\begin{document}
\pagestyle{plain}
\maketitle

\tableofcontents
\newpage
% Contenido.

%% Apéndices (ejercicios, exámenes)
\appendix
$extra_tex_files_input
\printindex
\end{document}
EOF


echo "Done."
