#!/bin/bash

course="$1"

tmpdir=/tmp/$course
ignorable_tex="tikzaux.tex"

if [ -z "$course" ]; then
	echo "Uso: pack [nombre curso]"
	exit
fi

if [ ! -d "$course" ]; then
	echo "El curso $course no existe en los apuntes."
	exit
fi

cd "$course"

if [ -d "$tmpdir" ]; then
	echo "Restaurando directorio temporal."
	rm -r "$tmpdir"
fi

mkdir -p "$tmpdir"

for tex in $(ls *.tex); do
	if [[ ! $ignorable_tex =~ "$tex" ]]; then
		cp -v $tex "$tmpdir"
	fi
done

cp -vr tex pdf "$tmpdir"
mkdir -p "${tmpdir}/tikz"
cp -vr tikz/*.tex "${tmpdir}/tikz"
cd ..
cd "Cosas Guays LaTeX"
cp -vr *.sty *.cls "$tmpdir"
cd ..
cwd=$(pwd)
cd $(dirname "$tmpdir")
zip -r "${cwd}/${course}.zip" "$(basename "$tmpdir")"



