\convs[arg0][arg1][arg2]#m
\convdist[arg0]#m
\convprob[arg0]#m
\convcs[arg0]#m
\begin{problem}[num]#
\begin{example}#
\begin{defn}[name]#
\begin{theorem}[name]#
\gen{arg0}#m
\ord{arg0}#m
\esp[arg0]{arg1}#m
\prob[arg0]{arg1}#m
\var[arg0]{arg1}#m
\sample[X]#