#!/bin/bash
latex_dir=$(dirname $(kpsewhich article.cls))
echo "Copying packages..."
cp -v ./*.sty $latex_dir
echo "Packages copied."
echo "Copying classes..."
cp -v ./*.cls $latex_dir
echo "Classes copied"
echo "Updating package cache..."
sudo texhash
echo "Package cache updated."
echo "Finished"
