#!/bin/bash
latex_dir=$(dirname $(kpsewhich article.cls))
echo "Creating completion file..."
python cwlcreator.py exmath.sty exmath.cwl
cp -vf *.cwl ~/.config/texstudio 
echo "Copying packages..."
cp -v *.sty $latex_dir
echo "Packages copied."
echo "Copying classes..."
cp -v *.cls $latex_dir
echo "Classes copied"
echo "Updating package cache..."
texhash
echo "Package cache updated."
echo "Finished"
